services:
  message:
    build:
      context: ../message
      dockerfile: ../message/Dockerfile
    image: message-server
    ports:
      - "8081:8081"
  user:
    build:
      context: ../user
      dockerfile: ../user/Dockerfile
    image: user-server
    ports:
      - "8082:8082"
  bff:
    build:
      context: ../bff
      dockerfile: ../bff/Dockerfile
    image: bff-server
    ports:
      - "8080:8080"
